preload = /home/virus/.config/hypr/fondo_actual

wallpaper {
	monitor = HDMI-A-1
	path = /home/virus/.config/hypr/fondo_actual
	fit_mode = cover
}

wallpaper {
	monitor =
	path = /home/virus/.config/hypr/fondo_actual
	fit_mode = cover
}

splash = false
