# Aumentamos el tiempo para evitar el error de [WARN]
scan_timeout = 120

# Definimos el orden: Logo de OS, espacio, Directorio, Carácter de entrada
format = """$os $directory$character"""

[os]
disabled = false
style = "bold blue"

[os.symbols]
Arch = "󰣇 "  # Este es el logo de Arch que usa Nerd Fonts

[directory]
style = "bold cyan"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
